In [13]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv("../data/raw/Housing.csv")

df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [4]:
binary_columns = [
    "mainroad",
    "guestroom",
    "basement",
    "hotwaterheating",
    "airconditioning",
    "prefarea"
]

df[binary_columns] = df[binary_columns].replace({
    "yes": 1,
    "no": 0
})

In [5]:
df[binary_columns].head()

  mainroad guestroom basement hotwaterheating airconditioning prefarea
0        1         0        0               0               1        1
1        1         0        0               0               1        0
2        1         0        1               0               0        1
3        1         0        1               0               1        1
4        1         1        1               0               1        0

In [6]:
df = pd.get_dummies(
    df,
    columns=["furnishingstatus"],
    drop_first=True,
    dtype=int
)

In [8]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1,0
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0,0

In [9]:
features = [
    "price",
    "area",
    "bedrooms",
    "stories",
    "parking",
    "mainroad",
    "guestroom",
    "basement",
    "hotwaterheating",
    "airconditioning",
    "prefarea",
    "furnishingstatus_semi-furnished",
    "furnishingstatus_unfurnished"
]

X = df[features].copy()

In [10]:
X.head()

,price,area,bedrooms,stories,parking,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,3,2,1,0,0,0,1,1,0,0
1,12250000,8960,4,4,3,1,0,0,0,1,0,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,1,1,0
3,12215000,7500,4,2,3,1,0,1,0,1,1,0,0
4,11410000,7420,4,2,2,1,1,1,0,1,0,0,0

In [11]:
X.shape

(545, 13)

In [12]:
X.isnull().sum()

price                              0
area                               0
bedrooms                           0
stories                            0
parking                            0
mainroad                           0
guestroom                          0
basement                           0
hotwaterheating                    0
airconditioning                    0
prefarea                           0
furnishingstatus_semi-furnished    0
furnishingstatus_unfurnished       0
dtype: int64

In [14]:
scaler = StandardScaler()

In [15]:
X_scaled = scaler.fit_transform(X)

In [16]:
X_scaled

array([[ 4.56636513,  1.04672629,  1.40341936, ...,  1.80494113,
        -0.84488844, -0.6964292 ],
       [ 4.00448405,  1.75700953,  1.40341936, ..., -0.55403469,
        -0.84488844, -0.6964292 ],
       [ 4.00448405,  2.21823241,  0.04727831, ...,  1.80494113,
         1.18358821, -0.6964292 ],
       ...,
       [-1.61432675, -0.70592066, -1.30886273, ..., -0.55403469,
        -0.84488844,  1.43589615],
       [-1.61432675, -1.03338891,  0.04727831, ..., -0.55403469,
        -0.84488844, -0.6964292 ],
       [-1.61432675, -0.5998394 ,  0.04727831, ..., -0.55403469,
        -0.84488844,  1.43589615]], shape=(545, 13))

In [17]:
X_scaled = pd.DataFrame(
    X_scaled,
    columns=X.columns
)

In [19]:
X_scaled.head()

,price,area,bedrooms,stories,parking,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,4.566365,1.046726,1.403419,1.378217,1.517692,0.405623,-0.465315,-0.734539,-0.219265,1.472618,1.804941,-0.844888,-0.696429
1,4.004484,1.757010,1.403419,2.532024,2.679409,0.405623,-0.465315,-0.734539,-0.219265,1.472618,-0.554035,-0.844888,-0.696429
2,4.004484,2.218232,0.047278,0.224410,1.517692,0.405623,-0.465315,1.361397,-0.219265,-0.679063,1.804941,1.183588,-0.696429
3,3.985755,1.083624,1.403419,0.224410,2.679409,0.405623,-0.465315,1.361397,-0.219265,1.472618,1.804941,-0.844888,-0.696429
4,3.554979,1.046726,1.403419,0.224410,1.517692,0.405623,2.149083,1.361397,-0.219265,1.472618,-0.554035,-0.844888,-0.696429

In [20]:
df.to_csv("../data/processed/cleaned_housing.csv", index=False)

In [21]:
X_scaled.to_csv("../data/processed/scaled_features.csv",index=False)

In [22]:
df = pd.read_csv("../data/processed/cleaned_housing.csv")

In [23]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1,0
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0,0

In [24]:
df_scaled = pd.read_csv("../data/processed/scaled_features.csv")

In [25]:
df_scaled.head()

,price,area,bedrooms,stories,parking,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,4.566365,1.046726,1.403419,1.378217,1.517692,0.405623,-0.465315,-0.734539,-0.219265,1.472618,1.804941,-0.844888,-0.696429
1,4.004484,1.757010,1.403419,2.532024,2.679409,0.405623,-0.465315,-0.734539,-0.219265,1.472618,-0.554035,-0.844888,-0.696429
2,4.004484,2.218232,0.047278,0.224410,1.517692,0.405623,-0.465315,1.361397,-0.219265,-0.679063,1.804941,1.183588,-0.696429
3,3.985755,1.083624,1.403419,0.224410,2.679409,0.405623,-0.465315,1.361397,-0.219265,1.472618,1.804941,-0.844888,-0.696429
4,3.554979,1.046726,1.403419,0.224410,1.517692,0.405623,2.149083,1.361397,-0.219265,1.472618,-0.554035,-0.844888,-0.696429